### ISSUE TITLE
Can't find module in PSGallery

### ISSUE THREAD

**Issue by OranguTech** [joel74/POSH-F5-BIGIP#12]
LTM Module is there (https://www.powershellgallery.com/packages/F5-LTM/), but search for F5-BIGIP, F5, BIGIP... not finding it. (Either web interface or find-module)

```
> Find-Module -Name "*F5*"

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.4.290              F5-LTM                              PSGallery            This module uses the REST A...
2.1.0                SCOrchDev-F5                        PSGallery            A wrapper around the F5 ico...
1.0.50               f5-deploy                           PSGallery            Deploy Scripts for F5
1.0.43               f5-apm                              PSGallery            This module is used to inte...
1.3                  F5-LTM-Helper                       PSGallery            A set of helper functions b...
```

**Comment by joel74** [comment]
Correct, F5-BIGIP is not actively maintained and has never been put in the PS Gallery.

**Comment by OranguTech** [comment]
Ah, that wasn't clear in the readme. (Which, TBF, says:
> Setup: Install the latest version of the module either by calling 'Install-Module F5-BIGIP' to retrieve it from the PowerShell Gallery (assuming you're using PSGet, included in PowerShell 5 and later).

I guess this is/was using a different API and is effectively abandoned? Regardless, I just got up and running w/ POSH-LTM-REST, which might let us keep our infrastructure-tests Pester-based and reduce our dependence on another department, so thank you for this/that!
