### ISSUE TITLE
Document Remove-PoolMember requires port

### ISSUE THREAD

**Issue by spuder** [joel74/POSH-F5-BIGIP#6]
I couldn't get Remove-PoolMember to work. It was not returning any errors, but wasn't removing the member. 

    Remove-PoolMember -PoolName 'foo' -Partition 'Common' -Name 'bar' -Verbose

It would be good to document that the 'Name' attribute requires that the port be part of the name

wrong
```
-Name 'bar'
```

correct
```
-Name 'bar:80'
```

**Comment by joel74** [comment]
Hi, I believe you're thinking about nodes, not pool members. Pool members always have a port specified as part of their name. This allows for the same node to service different pools on different ports. But that aside, you're right - Remove-PoolMember should probably throw a 'member not found' error when you try to remove a pool member that it can't locate.

**Comment by spuder** [comment]
Yes. That was the mistake. A warning 'member $member not found' would be helpful.

**Comment by joel74** [comment]
Ok, pull request made. Please review when you get a chance. Thanks.

**Comment by joel74** [comment]
Pull request merged. Closing this issue.
